# Generated by Django 5.2.1 on 2025-05-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('slug', models.SlugField(choices=[('about', 'О проекте'), ('rules', 'Правила')], primary_key=True, serialize=False, unique=True, verbose_name='Идентификатор')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
