# Generated by Django 5.2.1 on 2025-05-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={},
        ),
        migrations.AddField(
            model_name='page',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(choices=[('about', 'О проекте'), ('rules', 'Правила')], unique=True, verbose_name='Идентификатор'),
        ),
    ]
